name: Code Review Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Code Coverage
        run: echo "Coverage is going to happen"

      - name: Run Security Checks
        run: |
          npm audit --audit-level=moderate
          npm audit fix --force 

      - name: Verify Fixes
        run: npm audit --audit-level=moderate
