name: Dependency Updates

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' 

jobs:
  dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Dependabot
        uses: dependabot/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          directory: '/'  # Specify the directory where dependencies are located

      - name: Run Dependabot
        run: npx dependabot
