name: Dependency Updates

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' 

jobs:
  dependabot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Dependabot
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Run Dependabot
        run: echo "Running Dependabot..."
