name: Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  permissions:
    contents: read
    pages: write
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create deployment directory
        run: mkdir -p ${{ github.workspace }}/docs/

      - name: Copy README.md to deployment directory
        run: cp README.md ${{ github.workspace }}/docs/

      - name: Commit and push changes
        run: |
          cd ${{ github.workspace }}/docs/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Deploy README.md to GitHub Pages"
          git push origin main
