name: Build Documentation

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'  # Replace with your desired Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Install jsdoc
        run: npm install --save-dev jsdoc

      - name: Build Documentation
        run: |
          ./node_modules/.bin/jsdoc -r ./src -d ./docs
