name: Deploy Github Pages Documentation

on:
  push:
    branches:
      - main  # Set this to your default documentation branch
    paths:
      - 'docs/**'  # Trigger the workflow only on changes in the 'docs' directory
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.x'

      - name: Build documentation
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site

      - name: Output update notification
        run: echo "Documentation has been updated! View the live version [here](https://Mati-Shaikh.github.io/FreelancerPanel_WebProject/)."
