name: Scheduled Tasks

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
jobs:
  perform-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 21.x
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run maintenance task
        run: |
          # Add your maintenance task command here
          echo "Running scheduled task..."
          npm run maintenance-script

